# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0004_itinerarysegment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarysegment',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerarysegment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
