# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0006_auto_20170714_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarysegment',
            name='end_time',
            field=models.TimeField(default='12:00 PM'),
        ),
        migrations.AlterField(
            model_name='itinerarysegment',
            name='start_time',
            field=models.TimeField(default='12:00 PM'),
        ),
    ]
