# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0007_auto_20170714_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='location',
            field=models.CharField(default='Singapore', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerarysegment',
            name='end_time',
            field=models.TimeField(default='1:00 PM'),
        ),
    ]
