# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0008_auto_20170715_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='location',
        ),
    ]
