# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0009_remove_itinerary_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarysegment',
            name='duration',
        ),
    ]
