# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0010_remove_itinerarysegment_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarysegment',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='itinerarysegment',
            name='category',
            field=models.IntegerField(choices=[(0, 'Food'), (1, 'Museum'), (2, 'Outdoor'), (3, 'Shopping'), (4, 'Casino'), (5, 'Recreational'), (6, 'Photo-spot'), (7, 'Other')], default=0),
        ),
    ]
