# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0011_auto_20170719_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarysegment',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itinerarysegment',
            name='category',
            field=models.IntegerField(choices=[(0, 'Food'), (1, 'Educational'), (2, 'Outdoor'), (3, 'Games'), (4, 'Social'), (5, 'Shopping'), (6, 'Casino'), (7, 'Recreational'), (8, 'Photo-spot'), (9, 'Other')], default=0),
        ),
    ]
