# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0012_auto_20170719_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarysegment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
