# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0013_itinerarysegment_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarysegment',
            options={'ordering': ['day_number', 'start_time']},
        ),
    ]
