# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0015_auto_20170720_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, related_name='fav_by', to='triplan.Profile'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='public_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_users', to='triplan.Profile'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 8, 3)),
        ),
    ]
