# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0016_auto_20170803_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 8, 11)),
        ),
    ]
