# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplan', '0017_auto_20170811_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(max_length=2)),
                ('comment', models.CharField(max_length=200)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 8, 13)),
        ),
        migrations.AddField(
            model_name='review',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triplan.Itinerary'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triplan.Profile'),
        ),
    ]
